
name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image back
        env:
          DOCKERFILE: Dockerfile
          DOCKER_TAG: calixteair/calixteairdocker:eatMeApi
        run: |
          docker build -f $DOCKERFILE -t $DOCKER_TAG .

      - name: SSH to VPS and pull new Docker image
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          port: 1794
          script: |
            # Pull the latest image from DockerHub
            docker pull calixteair/calixteairdocker:eatMeApi

            # Navigate to the project directory (if needed)
            cd ${{ secrets.PATH_TO_DCOMPOSE }}

            # Restart the Docker containers with docker-compose
            docker-compose down
            docker-compose up -d
